### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [jbg/bitcoin-consensus#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by jbg** [comment]
Thanks for pointing this out. It seems that the [data-encoding crate](https://crates.io/crates/data-encoding) would be a good replacement. In other projects I've replaced rustc-serialize with serde, but it doesn't seem to handle simple encodings like hex/base64 as far as I can tell.

**Comment by jbg** [comment]
Or simply the [hex crate](https://crates.io/crates/hex).

**Comment by jbg** [comment]
Resolved in d8b14f9
